version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    user: ${DB_USER}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    shm_size: "1gb"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: bridge
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_PASSWORD=${DB_PASSWORD}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      - ZOOM_AUTH_CODE=${ZOOM_AUTH_CODE}
      - REDIRECT_URI=${REDIRECT_URI}
      - ZOOM_BASE_API=${ZOOM_BASE_API}
    expose:
      - 3002
    ports:
      - 3002:3002
    links:
      - db:db
    network_mode: bridge
